/**
 * Intent: Format CmiwReport as a human-readable Markdown document.
 * Guarantees: Valid Markdown with headers, tables, and lists.
 */

import type { CmiwReport } from '../types/report.js';

/**
 * Format a CMIW report as Markdown.
 *
 * Intent: Produce human-readable output for documentation or review.
 * Guarantees: Well-structured Markdown with sections for each analysis domain.
 */
export function formatMarkdown(report: CmiwReport): string {
  const lines: string[] = [];

  // Header
  lines.push('# CMIW Analysis Report');
  lines.push('');
  lines.push(`**Analyzed:** ${report.metadata.analyzedPath}`);
  lines.push(`**Date:** ${report.metadata.timestamp}`);
  lines.push(`**Version:** ${report.metadata.version}`);
  lines.push(`**LLM Enriched:** ${report.metadata.llmEnriched ? 'Yes' : 'No'}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total Files | ${report.metadata.totalFiles} |`);
  lines.push(`| Total Components | ${report.metadata.totalComponents} |`);
  lines.push(`| Total Relationships | ${report.metadata.totalRelationships} |`);
  lines.push(`| Analysis Time | ${report.metadata.analysisTimeMs}ms |`);
  lines.push('');

  // Architecture
  lines.push('## Architecture');
  lines.push('');
  lines.push(report.architecture.summary);
  lines.push('');

  if (report.architecture.patterns.length > 0) {
    lines.push('### Patterns Detected');
    lines.push('');
    for (const pattern of report.architecture.patterns) {
      lines.push(`- **${pattern.name}** (confidence: ${(pattern.confidence * 100).toFixed(0)}%)`);
      for (const evidence of pattern.evidence) {
        lines.push(`  - ${evidence}`);
      }
    }
    lines.push('');
  }

  if (report.architecture.layers.length > 0) {
    lines.push('### Layers');
    lines.push('');
    lines.push('| Layer | Type | Components |');
    lines.push('|-------|------|------------|');
    for (const layer of report.architecture.layers) {
      lines.push(`| ${layer.name} | ${layer.type} | ${layer.componentIds.length} |`);
    }
    lines.push('');
  }

  // Security
  lines.push('## Security');
  lines.push('');
  lines.push(`**Score:** ${report.security.score}/100 (Grade: ${report.security.grade})`);
  lines.push('');
  lines.push(report.security.summary);
  lines.push('');

  if (report.security.findings.length > 0) {
    lines.push('### Findings');
    lines.push('');
    lines.push('| Severity | Rule | Title | File | Line |');
    lines.push('|----------|------|-------|------|------|');
    for (const finding of report.security.findings) {
      const severity = finding.severity.toUpperCase();
      lines.push(`| ${severity} | ${finding.ruleId} | ${finding.title} | ${finding.filePath} | ${finding.startLine} |`);
    }
    lines.push('');
  }

  // Knowledge Graph
  lines.push('## Knowledge Graph');
  lines.push('');
  lines.push(`- **Nodes:** ${report.graph.nodes.length}`);
  lines.push(`- **Edges:** ${report.graph.edges.length}`);
  lines.push(`- **Clusters:** ${report.graph.clusters.length}`);
  lines.push(`- **Circular Dependencies:** ${report.graph.circularDependencies.length}`);
  lines.push('');

  if (report.graph.circularDependencies.length > 0) {
    lines.push('### Circular Dependencies');
    lines.push('');
    for (const cycle of report.graph.circularDependencies) {
      lines.push(`- ${cycle.path.join(' -> ')} (${cycle.severity})`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by CMIW*');

  return lines.join('\n');
}
